### ISSUE TITLE
Non-ascii characters are garbled

### ISSUE THREAD

**Issue by PeteBleackley** [prologic/sahriswiki#10]
See http://sources.conlang.org/Conlang_Critic for an example

My config file has the option encoding="utf-8" set.

**Comment by prologic** [comment]
I believe this is being discussed more over at circuits/circuits#186 right?

**Comment by PeteBleackley** [comment]
Correct. I did some digging and thought that it might be a circuits issue.

**Comment by prologic** [comment]
I think @spaceone just fixed it in circuits/circuits#187

**Comment by PeteBleackley** [comment]
Fix is now installed an working on sources.conlang.org Thanks

**Comment by prologic** [comment]
Awesome stuff! :) Be sure to thank @spaceone who actually fixed this!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
