### ISSUE TITLE
sahriswiki.org is down

### ISSUE THREAD

**Issue by PeteBleackley** [prologic/sahriswiki#6]
I'm interested in setting up a site using SahrisWiki, and have been trying to look at [your website](http://sahriswiki.org) for more information. Unfortunately, it's been down for most of this week.

**Comment by prologic** [comment]
So it is :) Let me fix that. http://prologic.shortcircuit.net.au/ is
powered by the same engine and is up :) I also need to fix the data stores
on these sites :) I fubared some of my home infra up but haven't fixed it
yet :)

cheers
James

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
It's back up now :)

Also this can be spun up with [Docker](https://www.docker.com)! Here's a `docker-compose.yml`:

``` #!yml
sahriswiki:
  image: prologic/sahriswiki
  environment:
    - VIRTUALHOST=sahriswiki.org
  restart: always
```

**Comment by prologic** [comment]
And a configuration that uses a local volume storage:

``` #!yml
prologic:
  image: prologic/sahriswiki
  environment:
    - VIRTUALHOST=prologic.shortcircuit.net.au
  volume_driver: local
  volumes:
    - prologicdata:/data
  command: -r /data/prologic/pages -d sqlite:////data/prologic.db -p 80 --debug
  restart: always
```

**Comment by prologic** [comment]
@PeteBleackley Any questions or feedback you have? Can I help in any way?

**Comment by PeteBleackley** [comment]
One thing I'd like to know about is using a bot to create pages on my sahriswiki instance. Would a single POST request to page/+Edit  with payload={'action':'save',
                 'text':page} work, or is there anything else I need to do?

**Comment by prologic** [comment]
This would work totally fine as it's a pretty normal HTML form that you just POST to.

However that being said; the "wiki pages" (content) are actually stored in a Mercurial repository which can be accessed/cloned/pushed-to/etc at /+hg/ -- So you could just get your bot to push commits to the underlying repository!

**Comment by PeteBleackley** [comment]
sahriswiki.org is down again. It's giving a 404 error for the main page.

**Comment by prologic** [comment]
Thanks for reporting :) Fixed! I forgot about my sahrswiki sites when
upgrading my infra to docker stack services proper!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
